Correctly split hg38 HLA contigs during configuration
When testing manta on hg38 full from the 1000 genomes distribution,
there are problems handling the HLA contigs, which contain colons: `HLA-A*01:01:01:01`.

Configuration fails with:
```
CONFIGURATION ERROR:
Reference fasta and 'Normal' BAM/CRAM file conflict on chromosome: 'HLA-A*01'
```
when splitting the names from the BAM tags. This small fix resolves the
problem. When running, there is also a downstream failure with a similar
problem trying to parse ranges in names with colons:
```
FATAL_ERROR: EstimateSVLoci EXCEPTION: ERROR: can't parse bam_region [err 1] HLA-A*01:01:01:02N:1-3291
```
I worked around this by excluding HLA regions from manta, with
`--region` but just as an additional related source of issues.